blank_issues_enabled: false
contact_links:
  - name: Shadps4 Troubleshooting/Support 
    url: https://discord.gg/qPvRetbWyk
    about: For support and technical issues, please come to our Discord server.
